baseURL = 'https://stark.software/'
locale = 'en_GB'
title = 'Stark Software'

disableKinds = ['rss', 'taxonomy', 'term']

[params]
description = 'Open-source macOS productivity tools and documentation.'

[[menu.main]]
name = 'Home'
url = '/'
weight = 1
[[menu.main]]
name = 'Stark'
url = '/stark/'
weight = 2
[[menu.main]]
name = 'swm'
url = '/swm/'
weight = 3
[[menu.main]]
name = 'skbd'
url = '/skbd/'
weight = 4

[[menu.footer]]
name = 'GitHub'
weight = 1
url = 'https://github.com/starkwm'
