baseURL = 'https://stark.software/'
languageCode = 'en-gb'
title = 'Stark Software'

disableKinds = ['rss', 'taxonomy', 'term']

[[menu.main]]
name = 'home'
url = '/'
weight = 1
[[menu.main]]
name = 'stark'
url = '/stark/'
weight = 2
[[menu.main]]
name = 'skbd v2'
url = '/skbd@2/'
weight = 3
[[menu.main]]
name = 'skbd'
url = '/skbd/'
weight = 4
[[menu.main]]
name = 'signalbox'
url = '/signalbox/'
weight = 5

[[menu.footer]]
name = 'GitHub'
weight = 1
url = 'https://github.com/starkwm'
